### PR TITLE
Force old version of espressif32

### LINKED ISSUE #127: Compilation error 'touch_pad_filter_start' was not declared in this scope
Hello,

I cloned the code
Entered the `ESP32LapTimer` folder
Then trying to upload:

```bash
pio run -e BOARD_OLD -t upload

src/Buttons.cpp: In function 'void newButtonSetup()':
src/Buttons.cpp:63:3: error: 'touch_pad_filter_start' was not declared in this scope
   touch_pad_filter_start(BUTTON1);
   ^~~~~~~~~~~~~~~~~~~~~~
src/Buttons.cpp:63:3: note: suggested alternative: 'touch_trigger_src_t'
Compiling .pio/build/BOARD_OLD/src/HardwareConfig.cpp.o
   touch_pad_filter_start(BUTTON1);
   ^~~~~~~~~~~~~~~~~~~~~~
   touch_trigger_src_t
src/Buttons.cpp:64:3: error: 'touch_pad_set_filter_period' was not declared in this scope
   touch_pad_set_filter_period(BUTTON1);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pio/build/BOARD_OLD/src/Laptime.cpp.o
*** [.pio/build/BOARD_OLD/src/Buttons.cpp.o] Error 1

```

### PR DESCRIPTION
**Pull request by Smeat**
The new version changes a bunch of things. Version 3.5.0 should work fine for now.

This should fix #127. @Z1gun can you confirm this fixes your issue?

### CODE REVIEW

**Comment by Z1gun** [comment]
Kevin,

Partially yes, problem has gone.

```
Environment      Status    Duration
---------------  --------  ------------
BOARD_DEFAULT    FAILED    00:01:12.550
BOARD_TTGO_LORA  FAILED    00:00:17.002
BOARD_OLD        SUCCESS   00:00:30.994
BOARD_WROOM      SUCCESS   00:00:30.816
```
```
Problem in Lora.cpp
'LoRa' was not declared in this scope
```

**Comment by Smeat** [comment]
50% there :)

Can you post the complete error message?
I am a little bit confused since I never merged LoRa support.

Just to clarify: To test this change use the normal repository and edit line 12 in platformio.ini to
```
platform = espressif32 @ ~3.5.0
```

**Comment by Z1gun** [comment]
Yes, I've just change this

`platform = espressif32 @ ~3.5.0`

This is a full compile error message about 'LoRa'

```
Archiving .pio\build\BOARD_TTGO_LORA\libd85\libSPI.a
src/Lora.cpp: In function 'void lora_send()':
src/Lora.cpp:49:12: error: 'LoRa' was not declared in this scope
   status = LoRa.beginPacket();
            ^
src/Lora.cpp: In function 'void lora_init(void*)':
src/Lora.cpp:89:3: error: 'LoRa' was not declared in this scope
   LoRa.setSPI(lora_spi);
   ^
src/Lora.cpp: In function 'void lora_update(void*)':
src/Lora.cpp:105:19: error: 'LoRa' was not declared in this scope
  int packetSize = LoRa.parsePacket();
                   ^
src/Lora.cpp: At global scope:
src/Lora.cpp:67:13: warning: 'void lora_send_task(void*)' defined but not used [-Wunused-function]
 static void lora_send_task(void* arg) {
             ^
Compiling .pio\build\BOARD_TTGO_LORA\lib525\WiFi\ETH.cpp.o
*** [.pio\build\BOARD_TTGO_LORA\src\Lora.cpp.o] Error 1
```

But maybe this is a not problem, because in this case 3 from 4 was successful 

```
Environment      Status    Duration
---------------  --------  ------------
BOARD_DEFAULT    SUCCESS   00:00:19.357
BOARD_TTGO_LORA  FAILED    00:00:04.479
BOARD_OLD        SUCCESS   00:00:04.549
BOARD_WROOM      SUCCESS   00:00:04.541
```

**Comment by Smeat** [comment]
It seems you have traces of my fork in you temporary files. If you delete the `.pio` folder, the errors should be gone

**Pull request merged**
